apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'svm-classifier'
        static_configs:
          - targets: ['svm-classifier-service:5002']
      - job_name: 'kubernetes-cadvisor'
        static_configs:
          - targets: ['cadvisor:8080']